services:
  pannoi_compose:
    image: pannoi
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        ROS_DISTRO: humble
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0', '3']
            capabilities: [gpu]
    stdin_open: true
    tty: true
    network_mode: host
    ipc: host
    privileged: true
    stop_grace_period: 1s
    environment:
      - ROS_DOMAIN_ID=101
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      # Mount X11 socket
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTHORITY:-$HOME/.Xauthority}:/root/.Xauthority
      # Mount .bashrc from host
      - ./docker/bashrc:/home/.bashrc:rw
      # Mount abu2024_ws
      - ./pannoi_ws:/home/pannoi_ws:rw

  navigation:
    extends: pannoi_compose
    command: bash -c "source ~/.bashrc && rviz2"

  gazebo:
    extends: pannoi_compose
    command: bash -c "source ~/.bashrc && gazebo"
